name: Build
on:
  push:
    branches:
      - master
      - develop
      - "*.*.*"
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: make ci-test
