name: Build
on:
  push:
    branches:
      - master
      - develop
      - "*.*.*"
  pull_request:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v2
      - name: Run Tests
        run: make ci-test
  release:
    name: Semantic Release
    needs: test
    uses: dividohq/shared-workflows/.github/workflows/build-release.yml@main
    secrets: inherit
    with:
      php_vendor_cache: true
