name: Build
on:
  push:
    branches:
      - master
      - develop
      - "*.*.*"
  pull_request:
jobs:
  setup:
    uses: dividohq/shared-workflows/.github/workflows/setup-composer.yml@main
    secrets: inherit
    
  test:
    uses: dividohq/shared-workflows/.github/workflows/test.yml@main
    needs: setup
    secrets: inherit
    with:
      php_vendor_cache: true

  release:
    uses: dividohq/shared-workflows/.github/workflows/release.yml@main
    needs: test
    secrets: inherit
