name: "Vetting"

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

jobs:
  pr-vetting:
    uses: dividohq/shared-workflows/.github/workflows/title-vetting.yml@main
    secrets: inherit
